spark-master:
  build: ./spark-master
  command: spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
  ports:
    - 4040:4040
    - 8042:8042
    - 7077:7077
    - 8080:8080
    - 8088:8088
  expose:
    - 4040
    - 8042
    - 7077
    - 8080
    - 8088
  links:
    - kafka

zookeeper:
  build: ./zookeeper
  hostname: zookeeper
  ports:
    - 2181:2181
  command: bash -c "kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties  && sleep 5s"

kafka:
  build: ./kafka
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 0
    KAFKA_HOST_NAME: 172.17.0.3 
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: 172.17.0.2:2181